In [135]:
import numpy as np
import pandas as pd

In [136]:
fifa = pd.read_csv("FIFA_2019.csv", index_col=0)

In [137]:
fifa
# 18207 rows x 88 columns

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,https://cdn.sofifa.org/teams/2/light/121.png,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,https://cdn.sofifa.org/teams/2/light/703.png,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,https://cdn.sofifa.org/teams/2/light/1944.png,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,https://cdn.sofifa.org/teams/2/light/15048.png,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,https://cdn.sofifa.org/teams/2/light/15048.png,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [138]:
for col in fifa.columns:
    print(col)

ID
Name
Age
Photo
Nationality
Flag
Overall
Potential
Club
Club Logo
Value
Wage
Special
Preferred Foot
International Reputation
Weak Foot
Skill Moves
Work Rate
Body Type
Real Face
Position
Jersey Number
Joined
Loaned From
Contract Valid Until
Height
Weight
LS
ST
RS
LW
LF
CF
RF
RW
LAM
CAM
RAM
LM
LCM
CM
RCM
RM
LWB
LDM
CDM
RDM
RWB
LB
LCB
CB
RCB
RB
Crossing
Finishing
HeadingAccuracy
ShortPassing
Volleys
Dribbling
Curve
FKAccuracy
LongPassing
BallControl
Acceleration
SprintSpeed
Agility
Reactions
Balance
ShotPower
Jumping
Stamina
Strength
LongShots
Aggression
Interceptions
Positioning
Vision
Penalties
Composure
Marking
StandingTackle
SlidingTackle
GKDiving
GKHandling
GKKicking
GKPositioning
GKReflexes
Release Clause

# Drop index/irrelevant variables (ID, photo, flag, club logo, real face, jersey number, loaned from)

In [139]:
fifa.drop(['ID','Photo','Flag','Club Logo','Real Face','Jersey Number','Loaned From'],
          axis=1,inplace=True)

In [140]:
fifa
# 18207 rows x 81 columns

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,1471,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,Right,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,Right,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,Right,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,Right,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,Right,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

# Drop goal keeper rows and variables

In [141]:
fifa['Position'].value_counts().sum()
#18147 rows with positions; 60 missing position values

18147

In [142]:
gk = fifa[fifa['Position'] == 'GK']
gk
fifa = fifa[fifa['Position'] != 'GK']
fifa
#16182 rows x 81 columns

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
5,E. Hazard,27,Belgium,91,91,Chelsea,€93M,€340K,2142,Right,...,91.0,34.0,27.0,22.0,11.0,12.0,6.0,8.0,8.0,€172.1M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,Right,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,Right,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,Right,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,Right,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,Right,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [143]:
fifa.drop(['GKDiving','GKHandling', 'GKPositioning', 'GKKicking', 'GKReflexes'],
          axis=1, inplace=True)
fifa
# 16182 rows x 76 columns

C:\Users\cnaga\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,€228.1M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,€196.4M
5,E. Hazard,27,Belgium,91,91,Chelsea,€93M,€340K,2142,Right,...,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,€172.1M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,Right,...,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,€143K
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,Right,...,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,€113K
18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,Right,...,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,€165K
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,Right,...,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,€143K
18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,Right,...,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,€165K

# Remove missing position

In [144]:
fifa = fifa[fifa['Position'].notna()]
fifa
# 16,122 rows x 76 columns

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,Left,...,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,€226.5M
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,Right,...,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,€127.1M
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,Right,...,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,€228.1M
4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,Right,...,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,€196.4M
5,E. Hazard,27,Belgium,91,91,Chelsea,€93M,€340K,2142,Right,...,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,€172.1M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,Right,...,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,€143K
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,Right,...,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,€113K
18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,Right,...,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,€165K
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,Right,...,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,€143K
18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,Right,...,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,€165K

# Examine remaining missing values

In [145]:
fifa.columns[fifa.isnull().any()].tolist()

['Club', 'Joined', 'Contract Valid Until', 'Release Clause']

In [146]:
fifa['Club'].isnull().sum()
# 196 Club variable will not be used because there are too many; will bin country instead

196

In [147]:
fifa['Joined'].isnull().sum()
#1371
noJoin = fifa[fifa['Joined'].isnull()]
noJoin

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Release Clause
28,J. Rodríguez,26,Colombia,88,89,FC Bayern München,€69.5M,€315K,2171,Left,...,64.0,55.0,80.0,89.0,81.0,87.0,52.0,41.0,44.0,NaN
38,G. Higuaín,30,Argentina,88,88,Milan,€57M,€245K,1965,Right,...,50.0,20.0,92.0,74.0,70.0,86.0,35.0,22.0,18.0,NaN
91,Paulinho,29,Brazil,85,85,Guangzhou Evergrande Taobao FC,€37M,€235K,2245,Right,...,81.0,81.0,84.0,78.0,71.0,80.0,75.0,81.0,73.0,NaN
166,Anderson Talisca,24,Brazil,83,90,Guangzhou Evergrande Taobao FC,€36.5M,€18K,2142,Left,...,67.0,58.0,86.0,81.0,71.0,74.0,55.0,62.0,42.0,NaN
176,M. Kovačić,24,Croatia,83,89,Chelsea,€35M,€165K,2115,Right,...,77.0,78.0,69.0,88.0,59.0,72.0,69.0,75.0,63.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17978,M. Bloomfield,21,England,51,57,Hamilton Academical FC,€50K,€3K,1277,Right,...,35.0,16.0,47.0,45.0,62.0,49.0,14.0,13.0,13.0,NaN
17979,Zhang Yuan,21,China PR,51,60,Guizhou Hengfeng FC,€60K,€2K,1459,Right,...,58.0,41.0,53.0,47.0,36.0,43.0,47.0,41.0,46.0,NaN
18026,Chen Ji,21,China PR,50,59,Guizhou Hengfeng FC,€50K,€2K,1440,Right,...,56.0,50.0,37.0,49.0,42.0,38.0,46.0,48.0,51.0,NaN
18031,Zhou Xin,20,China PR,50,61,Stabæk Fotball,€40K,€2K,1278,Right,...,54.0,54.0,43.0,38.0,38.0,32.0,51.0,48.0,48.0,NaN
18056,L. Valeau,19,Italy,50,65,Ascoli,€60K,€3K,1450,Left,...,60.0,49.0,26.0,49.0,40.0,42.0,41.0,54.0,55.0,NaN

In [148]:
fifa['Contract Valid Until'].isnull().sum()
#196

196

In [149]:
fifa['Release Clause'].isnull().sum()
#1379

1379

In [150]:
noRC = fifa[fifa['Release Clause'].isnull()]
noRC

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Release Clause
28,J. Rodríguez,26,Colombia,88,89,FC Bayern München,€69.5M,€315K,2171,Left,...,64.0,55.0,80.0,89.0,81.0,87.0,52.0,41.0,44.0,NaN
38,G. Higuaín,30,Argentina,88,88,Milan,€57M,€245K,1965,Right,...,50.0,20.0,92.0,74.0,70.0,86.0,35.0,22.0,18.0,NaN
91,Paulinho,29,Brazil,85,85,Guangzhou Evergrande Taobao FC,€37M,€235K,2245,Right,...,81.0,81.0,84.0,78.0,71.0,80.0,75.0,81.0,73.0,NaN
166,Anderson Talisca,24,Brazil,83,90,Guangzhou Evergrande Taobao FC,€36.5M,€18K,2142,Left,...,67.0,58.0,86.0,81.0,71.0,74.0,55.0,62.0,42.0,NaN
176,M. Kovačić,24,Croatia,83,89,Chelsea,€35M,€165K,2115,Right,...,77.0,78.0,69.0,88.0,59.0,72.0,69.0,75.0,63.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17978,M. Bloomfield,21,England,51,57,Hamilton Academical FC,€50K,€3K,1277,Right,...,35.0,16.0,47.0,45.0,62.0,49.0,14.0,13.0,13.0,NaN
17979,Zhang Yuan,21,China PR,51,60,Guizhou Hengfeng FC,€60K,€2K,1459,Right,...,58.0,41.0,53.0,47.0,36.0,43.0,47.0,41.0,46.0,NaN
18026,Chen Ji,21,China PR,50,59,Guizhou Hengfeng FC,€50K,€2K,1440,Right,...,56.0,50.0,37.0,49.0,42.0,38.0,46.0,48.0,51.0,NaN
18031,Zhou Xin,20,China PR,50,61,Stabæk Fotball,€40K,€2K,1278,Right,...,54.0,54.0,43.0,38.0,38.0,32.0,51.0,48.0,48.0,NaN
18056,L. Valeau,19,Italy,50,65,Ascoli,€60K,€3K,1450,Left,...,60.0,49.0,26.0,49.0,40.0,42.0,41.0,54.0,55.0,NaN

# Remove money symbols and convert to full value

In [151]:
def moneyConverter(Value):
    if isinstance(Value,str):
        out = Value.replace('€', '')
        if 'M' in out:
            out = float(out.replace('M', ''))*1000000
        elif 'K' in Value:
            out = float(out.replace('K', ''))*1000
        return float(out)

In [152]:
fifa['Value'] = fifa['Value'].apply(lambda x: moneyConverter(x))
fifa['Wage'] = fifa['Wage'].apply(lambda x: moneyConverter(x))
fifa['Release Clause'] = fifa['Release Clause'].apply(lambda x: moneyConverter(x))

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/2198156522.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Value'] = fifa['Value'].apply(lambda x: moneyConverter(x))
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/2198156522.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Wage'] = fifa['Wage'].apply(lambda x: moneyConverter(x))
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/2198156522.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Release Clause'] = fifa['Release Clause'].apply(lambda x: moneyConverter(x))

In [153]:
fifa

,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Marking,StandingTackle,SlidingTackle,Release Clause
0,L. Messi,31,Argentina,94,94,FC Barcelona,110500000.0,565000.0,2202,Left,...,48.0,22.0,94.0,94.0,75.0,96.0,33.0,28.0,26.0,226500000.0
1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000000.0,405000.0,2228,Right,...,63.0,29.0,95.0,82.0,85.0,95.0,28.0,31.0,23.0,127100000.0
2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500000.0,290000.0,2143,Right,...,56.0,36.0,89.0,87.0,81.0,94.0,27.0,24.0,33.0,228100000.0
4,K. De Bruyne,27,Belgium,91,92,Manchester City,102000000.0,355000.0,2281,Right,...,76.0,61.0,87.0,94.0,79.0,88.0,68.0,58.0,51.0,196400000.0
5,E. Hazard,27,Belgium,91,91,Chelsea,93000000.0,340000.0,2142,Right,...,54.0,41.0,87.0,89.0,86.0,91.0,34.0,27.0,22.0,172100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,J. Lundstram,19,England,47,65,Crewe Alexandra,60000.0,1000.0,1307,Right,...,46.0,46.0,39.0,52.0,43.0,45.0,40.0,48.0,47.0,143000.0
18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60000.0,1000.0,1098,Right,...,47.0,16.0,46.0,33.0,43.0,42.0,22.0,15.0,19.0,113000.0
18204,B. Worman,16,England,47,67,Cambridge United,60000.0,1000.0,1189,Right,...,32.0,15.0,48.0,43.0,55.0,41.0,32.0,13.0,11.0,165000.0
18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60000.0,1000.0,1228,Right,...,33.0,22.0,44.0,47.0,50.0,46.0,20.0,25.0,27.0,143000.0
18206,G. Nugent,16,England,46,66,Tranmere Rovers,60000.0,1000.0,1321,Right,...,56.0,42.0,34.0,49.0,33.0,43.0,40.0,43.0,50.0,165000.0

# Clean height

In [154]:
def cleanHeight(x):
    'Returns height in total inches'
    
    if isinstance(x,str):
        l=x.split("'")
        i=int(l[0])
        j=int(l[1])
        s=(i*12)+j
    return(s)

fifa['Height'] = fifa['Height'].apply(cleanHeight)

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/684971009.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Height'] = fifa['Height'].apply(cleanHeight)

In [155]:
fifa['Height']

0        67
1        74
2        69
4        71
5        68
         ..
18202    69
18203    75
18204    68
18205    70
18206    70
Name: Height, Length: 16122, dtype: int64

# Clean weight

In [156]:
def cleanWeight(x):
    'Removes lbs from value'
    
    if isinstance(x,str):
        return(x.replace('lbs', ''))
    return(x)

fifa['Weight'] = fifa['Weight'].apply(cleanWeight).astype('float')

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1258294178.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Weight'] = fifa['Weight'].apply(cleanWeight).astype('float')

In [157]:
fifa['Weight']

0        159.0
1        183.0
2        150.0
4        154.0
5        163.0
         ...
18202    134.0
18203    170.0
18204    148.0
18205    154.0
18206    176.0
Name: Weight, Length: 16122, dtype: float64

# Bin position

In [158]:
def binPosition(x):
    'Bins positions into forward, midfielder, defender'
    
    forward = ['LW', 'LF', 'ST', 'CF', 'RF', 'RW', 'LS', 'RS']
    midfielder = ['CAM', 'LM', 'CM', 'CDM', 'RM', 'LAM', 'LCM', 'LDM', 'RAM', 'RCM', 'RDM']
    defender = ['CB', 'LB', 'RB', 'LWB', 'RWB', 'LCB', 'RCB']
    
    
    if isinstance(x,str):
        if x in forward:
            return('Forward')
        elif x in midfielder:
            return('Midfielder')
        elif x in defender:
            return('defender')
        else:
            return(-1)

fifa['Position'] = fifa['Position'].apply(binPosition)
fifa['Position']

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/2395166040.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Position'] = fifa['Position'].apply(binPosition)

0           Forward
1           Forward
2           Forward
4        Midfielder
5           Forward
            ...
18202    Midfielder
18203       Forward
18204       Forward
18205       Forward
18206    Midfielder
Name: Position, Length: 16122, dtype: object

# Clean body type

In [160]:
fifa['Body Type'].value_counts()

Normal                 9143
Lean                   5969
Stocky                 1004
Messi                     1
C. Ronaldo                1
Neymar                    1
PLAYER_BODY_TYPE_25       1
Shaqiri                   1
Akinfenwa                 1
Name: Body Type, dtype: int64

In [161]:
fifa['Body Type'][fifa['Body Type'] == 'C. Ronaldo'] = 'Normal'
fifa['Body Type'][fifa['Body Type'] == 'PLAYER_BODY_TYPE_25'] = 'Normal'
fifa['Body Type'][fifa['Body Type'] == 'Akinfenwa'] = 'Stocky'
fifa['Body Type'][fifa['Body Type'] == 'Messi'] = 'Normal'
fifa['Body Type'][fifa['Body Type'] == 'Courtois'] = 'Normal'
fifa['Body Type'][fifa['Body Type'] == 'Shaqiri'] = 'Stocky'
fifa['Body Type'][fifa['Body Type'] == 'Neymar'] = 'Lean'

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'C. Ronaldo'] = 'Normal'
C:\Users\cnaga\anaconda3\lib\site-packages\pandas\core\generic.py:8870: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'PLAYER_BODY_TYPE_25'] = 'Normal'
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'Akinfenwa'] = 'Stocky'
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'Messi'] = 'Normal'
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'Courtois'] = 'Normal'
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'Shaqiri'] = 'Stocky'
C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/1968525046.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa['Body Type'][fifa['Body Type'] == 'Neymar'] = 'Lean'

# Clean skill rating variables

In [162]:
def skillConverter(val):
    'Adds skill rating to create one number'
    if type(val) == str:
        s1 = val[0:2]
        s2 = val[-1]
        val = int(s1) + int(s2)
        return val
    else:
        return val

skillColumns = ['LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM',
       'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM',
       'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB']

for col in skillColumns:
    fifa[col] = fifa[col].apply(skillConverter)

C:\Users\cnaga\AppData\Local\Temp/ipykernel_16832/3688070796.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fifa[col] = fifa[col].apply(skillConverter)

In [163]:
fifa['LS']

0        90
1        94
2        87
4        85
5        86
         ..
18202    44
18203    47
18204    47
18205    49
18206    45
Name: LS, Length: 16122, dtype: int64

In [165]:
fifa.to_csv('cleanFIFA.csv')